sudo: required
language: c++
osx_image: xcode9.4
os:
- linux
- osx

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install numpy==1.15; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sed -i '' 's/QTDIR = $(QTDIR_$(QT_VERSION))/QTDIR = \/usr\/local\/opt\/qt5/g' xcconfig/targetReleaseNionUILauncher.xcconfig; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sed -i '' 's/PYTHONHOME = $(HOME)\/Developer\/miniconda43/PYTHONHOME = \/usr\/local\/opt\/python3\/Frameworks\/Python.framework\/Versions\/3.7/g' xcconfig/targetReleaseNionUILauncher.xcconfig; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - python3-dev

script: bash travis-build.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "Sm0Dg91eVummvML2AHyN0g+klH7ETkWy3chtq2DL5SdvCorQNVPPCnksq7WqNTMv0oxjKbts56pRmDAVEIxA4AbWKP3AshP0iCjmO/viwxxNv8eFYKf+2Du+S/F5uOAm9aNSutRcoM4/+qN8JqzHVh56wqB7iidK/j7vbYk39opQI7QxKn58KE/m84d8+5/PpFIXrv+G3eeh4WnV6dEt1jrvp1T0WP94NnRF5igqcl3R9VQIqlTzWOeMtS6Qy3d2Kqj7BcylVPRbTggdqqVo9b7EKuvnd7UZtVFQoJxCuil+G61gmcnq2wayYWj3BF6PNnX8s2bCbaMaUJdcDkeM5PySBlI+CEdC/ZvU3ENe7nltn+a3lHLpCT0dCBV6PIDQFQOdN2afAoHQ17YRCxEb/CDV2/cduVwpvrn+KXIwqUqJXW1qUH23H1ZZtsuYISXkr29UgCe95TyFmvMsvXGUefqNOu5pCOYoZj84LONmoOXDUuCDoDwYf9rS4iY0yEXBJidv/FM6uI6f6CyUNv4ZGGoMmrs32m0a+cIWy/rwLsridKoHHeq1YlnbUFBPm6LtW0B/pMqNFN/65EcxfrEjf7SstsTmZcim60xu9oiqITqYHMzgoS/mwJhOQ6v95ZcJ+HatpX46w0uL/oWLBk9Y709GCFEA3CAOyz8VK06yzkE="
  file: release/*
  file_glob: true
  prerelease: true
  on:
    repo: nion-software/nionswift-launcher
    tags: true
