version: '#{build}'
image: Visual Studio 2017
platform: x64
configuration: Release

environment:
  QT_BASE_X64: C:\Qt\5.10.1\msvc2017_64
  PYTHON3_BASE_X64: C:\Miniconda36-x64

install:
- cmd: C:\Miniconda36-x64\Scripts\conda install numpy=1.12 -y

build:
  project: NionUILauncher.vcxproj
  verbosity: minimal

after_build:
  - ps: Get-ChildItem -Include *.pdb -Recurse | foreach { $_.Delete() }

artifacts:
- path: x64\Release\
  name: NionSwiftLauncher-Windows

deploy:
  provider: GitHub
  auth_token:
    secure: 2g4wtCmBBwxGrVylb2CV3woYIGgefAs6e9W+WmsrfS9v9U9vEFKEN2F5CddyAdI+
  artifact: /NionSwiftLauncher-Windows.zip/
  draft: false
  prerelease: false
  tag: $(appveyor_repo_tag_name)
  on:
    appveyor_repo_tag: true
